### ISSUE TITLE
Populate Countries

### ISSUE THREAD

**Issue by kmtracey** [rapidpro/rapidpro-community-portal#10]
Countries to choose from should be a full list of countries in the world. If they could be associated with continents to allow for chained select of continent then county that would be more user-friendly than a huge list of countries (suggestion from Kidus).

**Comment by emullaney** [comment]
World bank seems to have some pretty good data we can use... it just doesn't include continent. http://databank.worldbank.org/data/views/reports/metadataview.aspx#
