### ISSUE TITLE
Online course embeds from TechCharge

### ISSUE THREAD

**Issue by emullaney** [rapidpro/rapidpro-community-portal#115]
Expect more information in weekly call 6/24

**Comment by briseling** [comment]
Just waiting on URL to provide an external link for now.

**Comment by emullaney** [comment]
embed code https://basecamp.com/1849796/projects/8396121/messages/44802229

**Comment by emullaney** [comment]
Addressed in https://github.com/rapidpro/rapidpro-community-portal/pull/213, https://github.com/rapidpro/rapidpro-community-portal/pull/214, https://github.com/rapidpro/rapidpro-community-portal/pull/215
