### ISSUE TITLE
Gap between blog previews

### ISSUE THREAD

**Issue by hatlas** [rapidpro/rapidpro-community-portal#121]
A gap appears between previews on the main blog page on the desktop version of the site. It shows up where the fifth post should be if five or more posts appear on the page.
![screen shot 2015-06-17 at 2 02 59 pm](https://cloud.githubusercontent.com/assets/8808771/8215225/a3a2a7d8-14fc-11e5-9547-380c50e28b5a.png)

**Comment by emullaney** [comment]
This should be fixed once we merge in https://github.com/rapidpro/rapidpro-community-portal/pull/116

**Comment by hatlas** [comment]
Issue is now fixed.
