### ISSUE TITLE
On mobile, Youtube video changes width of page

### ISSUE THREAD

**Issue by hatlas** [rapidpro/rapidpro-community-portal#122]
If you're on mobile, the Youtube video on the homepage is wider than the intended width of the page, so by default the entire video doesn't display. To see the entire video you have to zoom out, leaving an empty margin on the right side of the page.
![screen shot 2015-06-17 at 4 13 38 pm](https://cloud.githubusercontent.com/assets/8808771/8217534/0c75f346-150c-11e5-9d33-084b120c0f2a.png)![screenshot_2015-06-17-16-11-48](https://cloud.githubusercontent.com/assets/8808771/8217562/37266508-150c-11e5-81e7-d6a91e506142.png)![screenshot_2015-06-17-16-11-54](https://cloud.githubusercontent.com/assets/8808771/8217563/3726929e-150c-11e5-9755-45e6137f1d6b.png)

**Comment by briseling** [comment]
expect the user to move to landscape mode.

**Comment by emullaney** [comment]
This was actually addressed when we found the proper css via wagtail team
