### ISSUE TITLE
Nav bar - "Connect" options misaligned in portrait mode on mobile

### ISSUE THREAD

**Issue by hatlas** [rapidpro/rapidpro-community-portal#123]
On mobile, when viewing the "connect" options in the nav bar in portrait mode, "User Forum" appears indented.
![screen shot 2015-06-17 at 4 25 37 pm](https://cloud.githubusercontent.com/assets/8808771/8217842/9993a204-150d-11e5-9d15-d710497aca62.png)

**Comment by emullaney** [comment]
duplicate issue with #125, closing this and merging these into one issue.
