### ISSUE TITLE
Install Disqus widget for Blog comments

### ISSUE THREAD

**Issue by briseling** [rapidpro/rapidpro-community-portal#126]
Will need to get credentials from Unicef team

**Comment by emullaney** [comment]
Note: I need to include this link in basecamp when we push this out.
https://rapidprocommunity.disqus.com/

**Comment by emullaney** [comment]
closed in https://github.com/rapidpro/rapidpro-community-portal/pull/162

**Comment by emullaney** [comment]
closed in https://github.com/rapidpro/rapidpro-community-portal/pull/162
