### ISSUE TITLE
Ensure uniqueness of various M2Ms assoc with case study and marketplace entries

### ISSUE THREAD

**Issue by kmtracey** [rapidpro/rapidpro-community-portal#13]
You should not be able to associate the same focus area (for example) more than once with a single case study, same for Country, etc. and any similar things associated with Marketplace entries. Right now we are allowing that. I'm guessing adding a unique_togethers in the various affected models will fix this.

**Comment by emullaney** [comment]
For through models (focus area, service, etc.) we cannot enforce unique_together per this https://groups.google.com/forum/#!topic/wagtail/zDe5ocpL5xA.

I'll work on filtering out duplicates on the templates, and when we work on the new views for user created entries, we can block duplication there as well.
