### ISSUE TITLE
Nav Rollover bg color

### ISSUE THREAD

**Issue by briseling** [rapidpro/rapidpro-community-portal#138]

**Comment by daaray** [comment]
I am taking this ticket title to relate to p12 of the PDF feedback doc.

**Comment by emullaney** [comment]
Tested this on IE on one of the virtual machines got some unexpected behavior:

![image](https://cloud.githubusercontent.com/assets/11393311/8416993/7eacb7dc-1e77-11e5-825a-8eca2315b1c7.png)

**Comment by emullaney** [comment]
mistakenly closed this issue nav rollover and current item color

**Comment by daaray** [comment]
The title of this ticket is confusing. If you look at Page 12, Item A; that appears to be what this ticket encapsulates.  If we agree on that, this ticket is closeable.  Page 12, Item C is represented in #137.

Thoughts?

**Comment by emullaney** [comment]
You are correct
