### ISSUE TITLE
Primary Navigation Links do not function at all levels.

### ISSUE THREAD

**Issue by daaray** [rapidpro/rapidpro-community-portal#148]
If I am at the root of the site, I can click back and forth between **Learn** and **Connect.

If I:
1. Click **Connect**
2. Click **Blog**
3. Click **Learn** --> nothing happens

**Comment by emullaney** [comment]
We are waiting on information from TechChange before we can work on that feature. It is a placeholder. This will be fixed in https://github.com/rapidpro/rapidpro-community-portal/issues/115 which is an enhancement.

**Comment by daaray** [comment]
Sorry, what I mean by nothing happens, in this context, is that when I follow the above steps, step 3 does not result in the page redrawing the sub menu for **Learn**, which I believe is the expected behavior?

**Comment by emullaney** [comment]
Oh weird, good call, the JS needs fixing.

**Comment by emullaney** [comment]
fixed by https://github.com/rapidpro/rapidpro-community-portal/pull/152
