### ISSUE TITLE
Stories pages - headers - decrease size 

### ISSUE THREAD

**Issue by emullaney** [rapidpro/rapidpro-community-portal#169]
Stories page-headers (Import the Flow, Focus Areas, Organisations, Tech Firms), please decrease the size to be the same as the eventual size of the highlight headers on the homepage. As for the U-Report or other Stories titles, we like the current size you’ve chosen so if you can maintain this for all Stories titles that would be great.

**Comment by kmtracey** [comment]
While I see the H2's are now H3's they appear to be using the same font size?
