### ISSUE TITLE
Update Case Study Index with updated CSS from Mockups

### ISSUE THREAD

**Issue by emullaney** [rapidpro/rapidpro-community-portal#19]
Updates found here https://github.com/rapidpro/rapidpro-community-portal/commit/d1b7d009cd696a2cba43a0bd0571203b7a3564fe

**Comment by kmtracey** [comment]
I think we need a little more UI guidance before this can be integrated. In general there will be multiple different types of things that can be filtered on (e.g. Country and Focus Area), so the filters on the left need to somehow show the type of thing in addition to the list of choices. We also need a search input not just the word Search? Also do we have UI guidance on how to reflect selected filters vs. ones that are not selected, number of hits, pagination?

**Comment by emullaney** [comment]
Additionally, remove the black circle (permalink) on upper right.

**Comment by briseling** [comment]
We can think about pagination maybe later.

**Comment by briseling** [comment]
Changes to CSS should be done to PR off of develop branch

**Comment by wraybowling** [comment]
Links, no bullet circles, separated by section with headers,

**Comment by copelco** [comment]
also need a search box.

**Comment by emullaney** [comment]
This has been fixed in the "mockups" branch. 
Closing this issue and creating a new ticket to create these templates with these updates and assigning that to myself.
