### ISSUE TITLE
Change feedback widget code

### ISSUE THREAD

**Issue by briseling** [rapidpro/rapidpro-community-portal#228]
Select edit mode to copy and paste this as I have left the comment tags in place.

<script>(function(){var uv=document.createElement('script');uv.type='text/javascript';uv.async=true;uv.src='//widget.uservoice.com/6KKtMK5orKjNsfbCUOdqA.js';var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(uv,s)})()</script>

<div data-uv-inline="classic_widget" data-uv-mode="feedback" data-uv-primary-color="#cc6d00" data-uv-link-color="#007dbf" data-uv-forum-id="298125" data-uv-feedback-tab_name="Submit an Idea" data-uv-width="100%" data-uv-height="550px"></div>

**Comment by emullaney** [comment]
Used settings found here instead to override the non-classic uservoice widget
https://developer.uservoice.com/docs/widgets/options/
