### ISSUE TITLE
"Get started now" not centered on IE

### ISSUE THREAD

**Issue by kmtracey** [rapidpro/rapidpro-community-portal#28]
Using IE11, the "Get started now" button that is supposed to be centered (vertically depending on height of neighboring featured case study area), isn't being centered. IE is showing a ghostly (apparently non-functional) scroll bar and the "button" is appearing half-off the top of the area. Something about the transform-center rules that applied to this area don't work for IE.

**Comment by wraybowling** [comment]
Ah.. The transforms need -ms- prefix. This is on my radar! I want to verify it with an actual IE browser though.

**Comment by wraybowling** [comment]
accidentally removed the fix in #74.

**Comment by emullaney** [comment]
TODO: copy these changes into DEV in a new branch
https://github.com/rapidpro/rapidpro-community-portal/commit/708ee1ebecc047caf46da0e359fbca4c8bc0b38f
