### ISSUE TITLE
Home page highlights text overlaps images when screen too narrow

### ISSUE THREAD

**Issue by kmtracey** [rapidpro/rapidpro-community-portal#31]
When the browser window is narrowed "too much" the text of the highlights on the home page overlaps the image. I would expect the text to move to underneath the image if the screen is too narrow for it to be to the right.

**Comment by wraybowling** [comment]
In order for images to scale, they need class="full". {% image hlight.icon max-140x140 %} doesn't have a way to add a class does it? I can come up with alternative solutions if not.

Also, I could use a hand pulling down the staging database/images so i can see highlights. I'll put a bug in your ear tomorrow.

**Comment by kmtracey** [comment]
Verified home page highlights text no longer overlaps images when the window is narrowed too far on Firefox, Chrome, and IE.
