### ISSUE TITLE
Case study - Display Month and Year only.

### ISSUE THREAD

**Issue by emullaney** [rapidpro/rapidpro-community-portal#39]
Kalee mentioned that we might need to remove dates from Case Studies. She will check on this and get back to us.

**Comment by kmtracey** [comment]
During discussion of this page, the "launch date" was suggested and got a positive response. It would be good to confirm it's not wanted with the full group before removing.

**Comment by emullaney** [comment]
Kidus: Month and year only. Let’s call it “Launch Date”

**Comment by emullaney** [comment]
This is covered by another issue #103
