### ISSUE TITLE
Marketplace Entry Form for user entry

### ISSUE THREAD

**Issue by emullaney** [rapidpro/rapidpro-community-portal#45]
Requirements from meeting 5/20
List of Fields for Marketplace Entry, that these should all be entered by the user, and that these are everything. Required fields starred.
[ ] Company name*
[ ] Add Company website under Company name
[ ] Company launch date\* - Change this to “Established” with year only
[ ] Company bio*
[ ] Countries of expertise
[ ] Add with Regions of experience
[ ] Expertise: Preset list with ability for user to add
[ ] Services: Preset list with ability for user to add
[ ] Contact Information (address, email, phone)

**Comment by emullaney** [comment]
Requirements from meeting 5/20
List of Fields for Marketplace Entry, that these should all be entered by the user, and that these are everything. Required fields starred.
[ ] Company name*
[ ] Add Company website under Company name
[ ] Company launch date* - Change this to  “Established” with year only
[ ] Company bio*
[ ] Countries of expertise
[ ] Add with Regions of experience
[ ] Expertise: Preset list with ability for user to add
[ ] Services: Preset list with ability for user to add
[ ] Contact Information (address, email, phone)

**Comment by briseling** [comment]
needs to allow logo input now.
