### ISSUE TITLE
Subnav implementation

### ISSUE THREAD

**Issue by kmtracey** [rapidpro/rapidpro-community-portal#46]
template: rapidpro_community_portal/templates/base.html
bar style

**Comment by kmtracey** [comment]
We now have the HTML/CSS for this, but we need javascript to dynamically change the specific nav/subnav shown to the user upon click of a top-level item (and on initial render based on request url rather than hard-coding one to be "selected").

Also the "selected" css looks a little odd to me, The box is oddly square compared to other site styling and is the text within it is not centered vertically.

**Comment by emullaney** [comment]
Closed. Opened new issue for the other sub nav changes.
