### ISSUE TITLE
UserVoice Enable Multilingual Forums

### ISSUE THREAD

**Issue by briseling** [rapidpro/rapidpro-community-portal#62]
Not entirely sure this is what is intended: http://feedback.uservoice.com/knowledgebase/articles/21515-setting-up-a-forum  Appears to allow you ot set "a" language for your forum. Does note appear to also translate the contents of your forum?

**Comment by briseling** [comment]
Look up this topic: "Language support for Forums" on this page: http://feedback.uservoice.com/knowledgebase/articles/100870-multi-language-options-for-your-uservoice-site Appears you can create a separate forum for each desired language. Will need to ask Unicef which languages they wish to support.

**Comment by briseling** [comment]
needs to support English, French, Spanish, Portughese and Arabic

**Comment by daaray** [comment]
I am fairly certain that @briseling set these up, as they are visible in the uservoice admin panel.
