### ISSUE TITLE
UserVoice - reskin the landing page

### ISSUE THREAD

**Issue by briseling** [rapidpro/rapidpro-community-portal#63]
match branding for new RapidPro community portal site.

**Comment by briseling** [comment]
Instructions appear to be here: ~~https://rapidpro1.uservoice.com/admin/settings/portal~~ https://feedback.uservoice.com/knowledgebase/articles/59012

**Comment by emullaney** [comment]
Place this text in the read me

Instructions for how to edit this in uservoice:
Sign on to http://rapidpro1.uservoice.com/
Then go to Admin Console (next to the user avatar)
Then pick Web Portal (from the gear under Settings)
Then Appearance and features
Then HTML/CSS/Javascript
I only modified the CSS and the Header

**Comment by briseling** [comment]
remove the nav links from User Voice landing page. Make the logo link to the site.

**Comment by briseling** [comment]
see if RapidPro logo can align with left column of user voice body text to match rapidpro site.
