### ISSUE TITLE
Need to style the forms

### ISSUE THREAD

**Issue by emullaney** [rapidpro/rapidpro-community-portal#67]

**Comment by emullaney** [comment]
Need styling around forms for Marketplace Entry Form:
Labels/inputs formatting for text inputs
Button for saving
Suggestion for any multi-selector? This will be to select things like Regions, Focus Areas, etc.

**Comment by wraybowling** [comment]
a plugin to consider: http://wenzhixin.net.cn/p/multiple-select/docs/#the-filter1

**Comment by emullaney** [comment]
![screenshot from 2015-06-01 15 21 51](https://cloud.githubusercontent.com/assets/11393311/7921246/38659282-0872-11e5-8306-68db1446d265.png)

inner scrollbar showing up on the form page

**Comment by emullaney** [comment]
Closing this, we implemented styling changes together as part of my work on the Marketplace Entry User form.
