### ISSUE TITLE
Home Page Highlights section css jumps around if text is long on one of the highlights.

### ISSUE THREAD

**Issue by emullaney** [rapidpro/rapidpro-community-portal#71]
Image describing the problem:
![screenshot from 2015-05-29 08 43 52](https://cloud.githubusercontent.com/assets/11393311/7883766/f956fa50-05e6-11e5-990c-0eebe9d86586.png)

**Comment by kmtracey** [comment]
Possibly a clue: this oddness seems to only happen when the "long" text is on the left hand side. The "long" Marketplace entry when positioned on the right hand side doesn't cause the lower items to have odd spacing.

**Comment by wraybowling** [comment]
There's two ways to solve this.
1. split the content into two halves, and fill the separate content columns with those halves. When the site squishes for mobile, the columns would stack (ie, the right side content would go below the left side content)
2. Masonry. http://masonry.desandro.com/

**Comment by wraybowling** [comment]
If we could include a div class="clear" after every two highlights, that would also fix it.

**Comment by wraybowling** [comment]
Trevor and I came up with a better solution. Thank goodness we're dropping IE9 and lower or else it wouldn't be possible. https://philipwalton.github.io/solved-by-flexbox/

Masonry might be necessary for search results though.

**Comment by kmtracey** [comment]
Verified long text on a non-bottom left highlight no longer has this effect of throwing off lower highlight formatting.

**Comment by kmtracey** [comment]
(Tested on IE11, Firefox, Chrome)
