### ISSUE TITLE
Search/filter front-end layout needs to be responsive

### ISSUE THREAD

**Issue by kmtracey** [rapidpro/rapidpro-community-portal#78]
Currently if you narrow the screen too much you get overlapping search filter text and page data, I'd expect the search sidebar instead to somehow accommodate a narrow screen by moving above (? possibly collapsed somehow?) the page content...

**Comment by emullaney** [comment]
screenshot describing the issue
![screenshot from 2015-06-02 16 22 59](https://cloud.githubusercontent.com/assets/11393311/7946272/b030c6d4-0943-11e5-8d5e-5ef40420e2cb.png)

**Comment by wraybowling** [comment]
![responsive filters](https://cloud.githubusercontent.com/assets/1120619/8015278/2ff991b2-0ba5-11e5-9742-52a3dd97476a.png)

**Comment by wraybowling** [comment]
fixed by #74
