### ISSUE TITLE
Full pre-QA Responsivness pass on all pages

### ISSUE THREAD

**Issue by briseling** [rapidpro/rapidpro-community-portal#81]
Add your known issues to be addressed here:
- [x] svg not rendering on any version of IE
- [x] wrapped blocks sometimes pick the wrong column to wrap on
- [x] flex layout elements of an odd number make the last item always 100% width

**Comment by wraybowling** [comment]
Lookin' good on these IE quirks so far!

**Comment by kmtracey** [comment]
Subnav styling has some issues on phone-size portrait. Top level unfortunately winds up wrapping, separating the chosen top-level item from the 2nd-level subnav. subnav items that are too long wrap, making them look like 2 different items (e.g. Knowlege as one item and Base as a 2nd). There also seems to be excessive space above the 1st subnav item on mobile (which doesn't seem to appear on desktop).

![screenshot_2015-06-09-14-37-05](https://cloud.githubusercontent.com/assets/430048/8066410/7e899e90-0eb5-11e5-8918-12969edcbe3f.png)

![screenshot_2015-06-09-14-35-19](https://cloud.githubusercontent.com/assets/430048/8066411/7e8adf9e-0eb5-11e5-91b1-aacb8df4a8df.png)
